config/routes.rb
Rails.application.routes.draw do
  resources :calendars do
    collection do
      get :index_for_user, as: :index_for_user
      get :index_for_operator, as: :index_for_operator
      post :index_commit, as: :index_commit
      post :index_for_user_commit, as: :index_for_user_commit
      post :index_for_operator_commit, as: :index_for_operator_commit
      get :zayavl
      get :uved
      get :prikaz
    end
  end
  resources :vocations
  resources :contracts
  resources :relations
  resources :posts
  resources :units
  resources :categories
  resources :workers
  resources :role_users
  get 'welcome/index', as: :index
  get 'welcome/insufficient_privileges', as: :ip

  resources :roles
  resources :user_sessions
  resources :users do
    member do
      get :activate
    end
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  root :to => 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/calendar.rb
class Calendar < ApplicationRecord
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController
  before_action :set_calendar, only: [:show, :edit, :update, :destroy]

  # GET /calendars
  # GET /calendars.json
  def index
    @year = params.has_key?(:year) ? params[:year].to_i : 2017

    @calendars = (Calendar.where(year_c: @year).order(:date_c).all)
    @hash = Hash.new{ |h, k| h[k] = [] }
    @calendars.each do |s|
      @hash[s.date_c.month] << s
    end

  end

  def index_for_user
    @year = params.has_key?(:year) ? params[:year].to_i : 2017
    @calendars = (Calendar.where(year_c: @year).order(:date_c).all)
    @hash = Hash.new{ |h, k| h[k] = [] }
    @vocations = Vocation.where("extract(year from d_conclusion_v) = :year OR extract(year from d_expiration_v ) = :year", year: @year).all
    @days = []
    @vocations.map{ |v|
      for i in v.d_conclusion_v..v.d_expiration_v
        @days << i
      end
    }
    @days.uniq!
    @calendars.each do |s|
      @hash[s.date_c.month] << s
    end

  end

  def index_for_operator
    @year = params.has_key?(:year) ? params[:year].to_i : 2017
    @calendars = (Calendar.where(year_c: @year).order(:date_c).all)
    @hash = Hash.new{ |h, k| h[k] = [] }
    @vocations = Vocation.where("extract(year from d_conclusion_v) = :year OR extract(year from d_expiration_v ) = :year", year: @year).all
    @days = []
    @vocations.map{ |v|
      for i in v.d_conclusion_v..v.d_expiration_v
        @days << i
      end
    }
    @days.uniq!
    @calendars.each do |s|
      @hash[s.date_c.month] << s
    end

  end

  # GET /calendars/1
  # GET /calendars/1.json
  def show
  end

  def index_commit
      (params[:day]).each do |key, value|
        obj= Calendar.find(key)
        if (value=="1")
          obj.is_output = true
        else
          obj.is_output = false
        end
        obj.save

      end
  end

  def index_for_user_commit
    y = User.find(params[:user_id])
    c = y.worker.contracts.first  # Выбрать текущий, а не первый контракт
    Vocation.where(contract_id: c.id).delete_all
    date_start = nil
    date_finish = nil
   i=0
    days = (params[:day])
    flag = 0

    days.each do |key, value|
      obj= Calendar.find(key)

      #  raise ((obj.date_c).class).inspect
      if (value=="1")
        if (flag==1)
         date_start = obj.date_c

        else
          flag = 1
          date_start = obj.date_c
          date_finish = obj.date_c

        end
       else
           if (flag==1)
             flag = 0
              # raise  date_finish.inspect
             x =  Vocation.create(type_v: "1" + i.to_s,
               d_conclusion_v: date_start, d_expiration_v: date_finish,
               is_real: "false", order_date: Date.today,
               order_number: "order_number " + i.to_s, contract_id: c.id)
           end
           i+=1

       end

    i+=1
    end
    @year = params.has_key?(:year) ? params[:year].to_i : 2017
    @calendars = (Calendar.where(year_c: @year).order(:date_c).all)
    @hash = Hash.new{ |h, k| h[k] = [] }
    @vocations = Vocation.where("extract(year from d_conclusion_v) = :year OR extract(year from d_expiration_v ) = :year", year: @year).all
    @days = []
    @vocations.map{ |v|
      for i in v.d_conclusion_v..v.d_expiration_v
        @days << i
      end
    }
    @days.uniq!
    @calendars.each do |s|
      @hash[s.date_c.month] << s
    end
    render(:index_for_user)
  end


  def zayavl
    send_file('/home/lety/111/public/1.pdf', :type => 'application/pdf',
      :disposition => 'inline', filename: 'qq.pdf')
  end

  def uved
    send_file('/home/lety/111/public/2.pdf', :type => 'application/pdf',
      :disposition => 'inline', filename: 'qq.pdf')
  end

  def prikaz
    send_file('/home/lety/111/public/3.pdf', :type => 'application/pdf',
      :disposition => 'inline', filename: 'qq.pdf')
  end


  def index_for_operator_commit
    y = User.find(params[:user_id])
    c = y.worker.contracts.first  # Выбрать текущий, а не первый контракт
    Vocation.where(contract_id: c.id).delete_all
    date_start = nil
    date_finish = nil
   i=0
    days = (params[:day])
    flag = 0

    days.each do |key, value|
      obj= Calendar.find(key)

      #  raise ((obj.date_c).class).inspect
      if (value=="1")
        if (flag==1)
         date_start = obj.date_c

        else
          flag = 1
          date_start = obj.date_c
          date_finish = obj.date_c

        end
       else
           if (flag==1)
             flag = 0
              # raise  date_finish.inspect
             x =  Vocation.create(type_v: "1" + i.to_s,
               d_conclusion_v: date_start, d_expiration_v: date_finish,
               is_real: "false", order_date: Date.today,
               order_number: "order_number " + i.to_s, contract_id: c.id)
           end
           i+=1

       end

    i+=1
    end
    @year = params.has_key?(:year) ? params[:year].to_i : 2017
    @calendars = (Calendar.where(year_c: @year).order(:date_c).all)
    @hash = Hash.new{ |h, k| h[k] = [] }
    @vocations = Vocation.where("extract(year from d_conclusion_v) = :year OR extract(year from d_expiration_v ) = :year", year: @year).all
    @days = []
    @vocations.map{ |v|
      for i in v.d_conclusion_v..v.d_expiration_v
        @days << i
      end
    }
    @days.uniq!
    @calendars.each do |s|
      @hash[s.date_c.month] << s
    end
    render(:index_for_user)
  end
    # @vocation_days = 28
    # (params[:day]).each do |key, value|
    #   obj= Calendar.find(key)
    #   if (value=="1")
    #
    #   else
    #
    #   end
    #   obj.save
    # end
    # end
      # ---
      # если несколько раз подрят да, записываем
      # когда встречается нет, прерываем
      # записываем кусок из да


  # GET /calendars/new
  def new
    @calendar = Calendar.new
  end

  # GET /calendars/1/edit
  def edit
  end

  # POST /calendars
  # POST /calendars.json
  def create
    @calendar = Calendar.new(calendar_params)
    dstart = Date.new(@calendar.year_c, 1, 1)
    dfinish = Date.new(@calendar.year_c + 1, 1, 1)
    while dstart < dfinish
      cld = Calendar.new
      cld.year_c = @calendar.year_c
      cld.date_c = dstart
      cld.is_output = (dstart.wday == 6 or dstart.wday == 0 ? true : false)
      cld.save
      dstart = dstart + 1.day
    end

    respond_to do |format|
      format.html { redirect_to calendars_path(year: @calendar.year_c), notice: 'Calendar was successfully created.' }
    end
  end

  # PATCH/PUT /calendars/1
  # PATCH/PUT /calendars/1.json
  def update
    respond_to do |format|
      raise @calendar.inspect

      if @calendar.update(calendar_params)
        format.html { redirect_to @calendar, notice: 'Calendar was successfully updated.' }
        format.json { render :show, status: :ok, location: @calendar }
      else
        format.html { render :edit }
        format.json { render json: @calendar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calendars/1
  # DELETE /calendars/1.json
  def destroy
    @calendar.destroy
    respond_to do |format|
      format.html { redirect_to calendars_url, notice: 'Calendar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calendar
      @calendar = Calendar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calendar_params
      params.require(:calendar).permit(:date_c, :is_output, :year_c)
    end


    private
    ## Проверка прав доступа выбранной роли для данного метода
    def check_ctr_auth()
      return true
    end

end

app/helpers/calendars_helper.rb
module CalendarsHelper
  def month_names
    {1 => 'Январь', 2 => 'Февраль', 3 => 'Март', 4 => 'Апрель',
      5 => 'Май', 6 => 'Июнь', 7 => 'Июль', 8 => 'Август', 9 => 'Сентябрь',
        10 => 'Октябрь', 11 => 'Ноябрь', 12 => 'Декабрь'}
  end
end

app/views/calendars/_form.html.haml
= form_for @calendar do |f|
  - if @calendar.errors.any?
    #error_explanation
      %h2= "#{pluralize(@calendar.errors.count, "error")} prohibited this calendar from being saved:"
      %ul
        - @calendar.errors.full_messages.each do |message|
          %li= message



  .field
    = f.label :year_c
    = f.number_field :year_c
  .actions
    = f.submit 'Save'

app/views/calendars/edit.html.haml
%h1 Editing calendar

= render 'form'

= link_to 'Show', @calendar
\|
= link_to 'Back', calendars_path

app/views/calendars/index.html.haml
= form_tag index_commit_calendars_path() do
  %h1
    Производственный календарь
    .pull-right
      = submit_tag 'Сохранить', class: 'btn btn-warning btn-lg'
      = submit_tag 'Импорт из внешних источников', class: 'btn btn-success btn-lg'
    .clearfix
  %h4
    Пятидневная рабочая неделя
  %br
  - @hash.each do |month, days|
    .box450.my_vertical_align
      %div
        %span.label.label-warning.label-lg
          = month_names[month]
        -flag = 1
      %div
        - day = days.first
        -if (flag== 1)
          -(flag=0)
          -case (wdayy = day.date_c.wday)
          -when 0
            -6.times do
              %span.box50.cal-field-empty
                = link_to(1, ?#, class: 'btn day_empty day_btn')
          -when 1..6
            -(wdayy-1).times do
              %span.box50.cal-field-empty
                = link_to(1, ?#, class: 'btn day_empty day_btn')
        - days.each do |day|
          %span.box50.buttons-hover.cal-field
            - if day.is_output == true
              = link_to(day.date_c.day, day, class: 'btn weekends_color day_btn')
              =hidden_field_tag "day[#{day.id}]", 1, class: 'day_hid'
            - else
              = link_to(day.date_c.day, day, class: 'btn day_btn')
              =hidden_field_tag "day[#{day.id}]", 0,  class: 'day_hid'
          - if day.date_c.wday == 0
            %br

          -# =raise (day.date_c.wday).to_s
          -# %span.box50.buttons-hover
          -#   - if day.date_c.wday == 0 or day.date_c.wday == 6
          -#     = link_to(day.date_c.day, day, class: 'btn weekends_color day_btn')
          -#     =hidden_field_tag "day[#{day.id}]", 1, class: 'day_hid'
          -#   - else
          -#     = link_to(day.date_c.day, day, class: 'btn day_btn')
          -#     =hidden_field_tag "day[#{day.id}]", 0,  class: 'day_hid'
          -# - if day.date_c.wday == 0
            %br

app/views/calendars/index_for_operator.html.haml
= form_tag index_for_user_commit_calendars_path(), class: :hide, id: :cancel_form do
  %h2 Введите причину отклонения
  = text_field_tag :cancel_reason, '', size: 80
  = link_to(?#, class: 'btn btn-primary', id: 'cancel1_finish') do
    = fa_icon 'arrow-right'
= form_tag index_for_user_commit_calendars_path() do
  = hidden_field_tag(:user_id, @current_user_object.id)
  = hidden_field_tag(:year, @year)
  %h1
    Утверждение отпуска сотрудника

  %h2
    Смирнов Михаил Александрович
.row
  .label.label-default.sqlabel
    .big
      = "Отдел по развитию производственной системы"
    .tiny
      = Worker.human_attribute_name(:Подразделение)
  .label.label-info.sqlabel
    .big
      = "Менеджер по развитию"
    .tiny
      = Worker.human_attribute_name(:Должность)
  .label.label-warning.sqlabel
    .big
      = "28"
    .tiny
      = Worker.human_attribute_name(:"Кол-во дней отпуска")
  .label.label-success.sqlabel
    .big
      = "13 (15)"
    .tiny
      = Worker.human_attribute_name(:"Распределено дней")
  %br
  %ol
    %li
      С 09.01.2018 до 12.01.2018: 4 дня.
    %li
      С 24.02.2018 до 04.03.2018: 9 дней.
  %h2
    Коррекция
  .row
    .col-md-9
      - @hash.each do |month, days|
        .box450.my_vertical_align
          %div
            %span.label.label-warning.label-lg
              = month_names[month]
            -flag = 1
          %div
            - day = days.first
            -if (flag== 1)
              -(flag=0)
              -case (wdayy = day.date_c.wday)
              -when 0
                -6.times do
                  %span.box50.cal-field-empty
              -when 1..6
                -(wdayy-1).times do
                  %span.box50.cal-field-empty
            - days.each do |day|
              %span.box50.buttons-hover.cal-field
                -# - raise [@days.inspect
                - if @days.include?(day.date_c) and day.is_output == true
                  = link_to(day.date_c.day, day, class: 'btn vocations_color weekends_color day_btn2')
                  =hidden_field_tag "day[#{day.id}]", 1, class: 'day_hid'
                - elsif @days.include?(day.date_c)
                  = link_to(day.date_c.day, day, class: 'btn vocations_color day_btn2')
                  =hidden_field_tag "day[#{day.id}]", 1, class: 'day_hid'
                - elsif day.is_output == true
                  = link_to(day.date_c.day, day, class: 'btn weekends_color day_btn2')
                  =hidden_field_tag "day[#{day.id}]", 0, class: 'day_hid'
                - else
                  = link_to(day.date_c.day, day, class: 'btn day_btn2')
                  =hidden_field_tag "day[#{day.id}]", 0,  class: 'day_hid'
              - if day.date_c.wday == 0
                %br
    .col-md-3
      = button_tag  class: 'btn btn-success btn-lg btn-fixed-size' do
        = fa_icon :check
        Утвердить
      %br
      = button_tag class: 'btn btn-easydanger btn-lg btn-fixed-size', id: 'cancel1' do
        = fa_icon :times
        Отклонить
      %br
      = link_to uved_calendars_path(format: :pdf), class: 'btn btn-default btn-lg btn-fixed-size' do
        = fa_icon :print
        Печать уведомления
      = link_to zayavl_calendars_path(format: :pdf),  class: 'btn btn-default btn-lg btn-fixed-size' do
        = fa_icon :print
        Печать заявления
      = link_to prikaz_calendars_path(format: :pdf),  class: 'btn btn-default btn-lg btn-fixed-size' do
        = fa_icon :print
        Печать приказа
    .clearfix

app/views/calendars/index_for_user.html.haml
= form_tag index_for_user_commit_calendars_path() do
  = hidden_field_tag(:user_id, @current_user_object.id)
  = hidden_field_tag(:year, @year)
  %h1
    Выбор периода отпуска
    .pull-right
      = submit_tag 'Сохранить', class: 'btn btn-warning btn-lg'
      = submit_tag 'Отправить на проверку', class: 'btn btn-success btn-lg'
      = submit_tag 'Печать', class: 'btn btn-default btn-lg'
    .clearfix
  %h2
    Смирнов Михаил Александрович
.row
  .label.label-default.sqlabel
    .big
      = "Отдел по развитию производственной системы"
    .tiny
      = Worker.human_attribute_name(:Подразделение)
  .label.label-success.sqlabel
    .big
      = "Менеджер по развитию"
    .tiny
      = Worker.human_attribute_name(:Должность)
  .label.label-warning.sqlabel
    .big
      = "28"
    .tiny
      = Worker.human_attribute_name(:"Кол-во дней отпуска")
  %br
%br
  - @hash.each do |month, days|
    .box450.my_vertical_align
      %div
        %span.label.label-warning.label-lg
          = month_names[month]
        -flag = 1
      %div
        - day = days.first
        -if (flag== 1)
          -(flag=0)
          -case (wdayy = day.date_c.wday)
          -when 0
            -6.times do
              %span.box50.cal-field-empty
          -when 1..6
            -(wdayy-1).times do
              %span.box50.cal-field-empty
        - days.each do |day|
          %span.box50.buttons-hover.cal-field
            -# - raise [@days.inspect
            - if @days.include?(day.date_c) and day.is_output == true
              = link_to(day.date_c.day, day, class: 'btn vocations_color weekends_color day_btn2')
              =hidden_field_tag "day[#{day.id}]", 1, class: 'day_hid'
            - elsif @days.include?(day.date_c)
              = link_to(day.date_c.day, day, class: 'btn vocations_color day_btn2')
              =hidden_field_tag "day[#{day.id}]", 1, class: 'day_hid'
            - elsif day.is_output == true
              = link_to(day.date_c.day, day, class: 'btn weekends_color day_btn2')
              =hidden_field_tag "day[#{day.id}]", 0, class: 'day_hid'
            - else
              = link_to(day.date_c.day, day, class: 'btn day_btn2')
              =hidden_field_tag "day[#{day.id}]", 0,  class: 'day_hid'
          - if day.date_c.wday == 0
            %br

app/views/calendars/new.html.haml
%h1 New calendar

= render 'form'

= link_to 'Back', calendars_path

app/views/calendars/show.html.haml
%p#notice= notice

%p
  %b Date c:
  = @calendar.date_c
%p
  %b Is output:
  = @calendar.is_output
%p
  %b Year c:
  = @calendar.year_c

= link_to 'Edit', edit_calendar_path(@calendar)
\|
= link_to 'Back', calendars_path