config/routes.rb
Rails.application.routes.draw do
  resources :calendars do
    collection do
      get :index_for_user, as: :index_for_user
      get :index_for_operator, as: :index_for_operator
      post :index_commit, as: :index_commit
      post :index_for_user_commit, as: :index_for_user_commit
      post :index_for_operator_commit, as: :index_for_operator_commit
      get :zayavl
      get :uved
      get :prikaz
    end
  end
  resources :vocations
  resources :contracts
  resources :relations
  resources :posts
  resources :units
  resources :categories
  resources :workers
  resources :role_users
  get 'welcome/index', as: :index
  get 'welcome/insufficient_privileges', as: :ip

  resources :roles
  resources :user_sessions
  resources :users do
    member do
      get :activate
    end
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  root :to => 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :category
  has_many :relations

  validates :name_p, presence: true
  validates :full_name_p, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Должность успешно создана.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Должность успешно отредактирована.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Должность успешно удалена.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name_p, :full_name_p, :category_id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.haml
= form_for @post do |f|
  - if @post.errors.any?
    #error_explanation
      %h2= "#{pluralize(@post.errors.count, "error")} prohibited this post from being saved:"
      %ul
        - @post.errors.full_messages.each do |message|
          %li= message

  .row
    .col-md-6
      .form-group
        = f.label :"Краткое наименование должности"
        = f.text_area :name_p, class: "form-control"
  .row
    .col-md-6
      .form-group
      = f.label :"Полное наименование должности"
      = f.text_area :full_name_p, class: "form-control"
  .row
    .col-md-6
      .form-group
      = f.label :"Категория"
      = f.text_field :category, class: "form-control"
  .row
    .col-md-6
      .form-group
  .form-actions
    = f.submit 'Сохранить', class: "btn btn-success"
    \|
    = link_to 'Назад', posts_path, class: "btn btn-success"

app/views/posts/edit.html.haml
%h1 Редактирование информации о должности

= render 'form'

= link_to 'Просмотр', @post, class: "btn btn-warning"

app/views/posts/index.html.haml
%h1 Должности

= link_to 'Добавить должность', new_post_path, class: "btn btn-warning"

%table.table
  %thead
    %tr
      %th Краткое наименование должности
      %th Полное наименование должности
      %th Категория
      %th
      %th
      %th

  %tbody
    - @posts.each do |post|
      %tr
        %td= post.name_p
        %td= post.full_name_p
        %td= post.category
        %td= link_to 'Показать', post, class: "btn btn-warning"
        %td= link_to 'Редактировать', edit_category_path(post), class: "btn btn-default "
        %td= link_to 'Удалить', post, method: :delete, data: { confirm: 'Вы уверены?' }, class: "btn btn-danger"

%br

app/views/posts/new.html.haml
%h1 Добавление должности

= render 'form'

app/views/posts/show.html.haml
%p#notice= notice

%p
  %b Краткое наименование должности:
  = @post.name_p
%p
  %b Полное наименование должности:
  = @post.full_name_p
%p
  %b Категория:
  = @post.category

= link_to 'Редактирование', edit_post_path(@post), class: "btn btn-default"
\|
= link_to 'Назад', posts_path,   class: "btn btn-warning"