config/routes.rb
Rails.application.routes.draw do
  resources :calendars do
    collection do
      get :index_for_user, as: :index_for_user
      get :index_for_operator, as: :index_for_operator
      post :index_commit, as: :index_commit
      post :index_for_user_commit, as: :index_for_user_commit
      post :index_for_operator_commit, as: :index_for_operator_commit
      get :zayavl
      get :uved
      get :prikaz
    end
  end
  resources :vocations
  resources :contracts
  resources :relations
  resources :posts
  resources :units
  resources :categories
  resources :workers
  resources :role_users
  get 'welcome/index', as: :index
  get 'welcome/insufficient_privileges', as: :ip

  resources :roles
  resources :user_sessions
  resources :users do
    member do
      get :activate
    end
  end

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout
  root :to => 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/unit.rb
class Unit < ApplicationRecord
  belongs_to :unit
  has_many :relations

  validates :name_u, presence: true
  validates :full_name_u, presence: true

end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_action :set_unit, only: [:show, :edit, :update, :destroy]

  # GET /units
  # GET /units.json
  def index
    @units = Unit.all
  end

  # GET /units/1
  # GET /units/1.json
  def show
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
  end

  # POST /units
  # POST /units.json
  def create
    @unit = Unit.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to @unit, notice: 'Подразделение успешно создано.' }
        format.json { render :show, status: :created, location: @unit }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to @unit, notice: 'Подразделение успешно отредактировано.' }
        format.json { render :show, status: :ok, location: @unit }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    @unit.destroy
    respond_to do |format|
      format.html { redirect_to units_url, notice: 'Подразделение успешно удалено.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = Unit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:name_u, :full_name_u, :unit_id)
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.haml
= form_for @unit do |f|
  - if @unit.errors.any?
    #error_explanation
      %h2= "#{pluralize(@unit.errors.count, "error")} prohibited this unit from being saved:"
      %ul
        - @unit.errors.full_messages.each do |message|
          %li= message
  .row
    .col-md-6
      .form-group
        = f.label :"Краткое наименование подразделения"
        = f.text_area :name_u, class: "form-control"
  .row
    .col-md-6
      .form-group
      = f.label :"Полное наименование подразделения"
      = f.text_area :full_name_u, class: "form-control"
  .row
    .col-md-6
      .form-group
      = f.label :"Подразделение"
      = f.text_field :unit, class: "form-control"
  .row
    .col-md-6
      .form-group
  .form-actions
    = f.submit 'Сохранить', class: "btn btn-success"
    \|
    = link_to 'Назад', units_path, class: "btn btn-success"

app/views/units/edit.html.haml
%h1 Editing unit

= render 'form'

= link_to 'Просмотр', @unit, class: "btn btn-warning"

app/views/units/index.html.haml
%h1 Подразделения

= link_to 'Добавить подразделение', new_unit_path, class: "btn btn-warning"

%table.table
  %thead
    %tr
      %th Краткое наименование подразделения
      %th Полное наименование подразделения
      %th Подразделение
      %th
      %th
      %th

  %tbody
    - @units.each do |unit|
      %tr
        %td= unit.name_u
        %td= unit.full_name_u
        %td= unit.unit
        %td= link_to 'Показать', unit, class: "btn btn-warning"
        %td= link_to 'Редактировать', edit_unit_path(unit), class: "btn btn-default "
        %td= link_to 'Удалить', unit, method: :delete, data: { confirm: 'Вы уверены?' }, class: "btn btn-danger"

%br

app/views/units/new.html.haml
%h1 Добавить подразделение

= render 'form'

app/views/units/show.html.haml
%p#notice= notice

%p
  %b Краткое наименование подразделения:
  = @unit.name_u
%p
  %b Полное наименование подразделения:
  = @unit.full_name_u
%p
  %b Подразделение:
  = @unit.unit

= link_to 'Редактирование', edit_unit_path(@unit), class: "btn btn-default"
\|
= link_to 'Назад', units_path,   class: "btn btn-warning"